weather/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weatherapi.urls', namespace='app')),
]

weatherapi/api/urls.py
from django.urls import path
from .views import OutputDataView, InputDataView
from django.views.decorators.cache import cache_page
from django.conf import settings

CACHE_TTL = settings.CACHE_TTL


app_name = 'api'
urlpatterns = [
    path('weather-list/', cache_page(CACHE_TTL)(OutputDataView.as_view()), name = 'weather-list'),
    path('input-list/', cache_page(CACHE_TTL)(InputDataView.as_view()), name = 'input-list'),
]

weatherapi/urls.py
from django.urls import path, include
from . import views

app_name = 'weatherapi'
urlpatterns = [
    path('api/', include('weatherapi.api.urls', namespace='app:api')),
    path('', views.home),
    path('clear-data/', views.clear_data, name='clear-data'),
]

weatherapi/models.py
from django.db import models


# Create your models here.
class InputData(models.Model):
    date = models.DateField()
    time = models.TimeField()
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    hight_ug = models.IntegerField()
    temperature = models.IntegerField()
    wind_speed = models.IntegerField()
    wind_vector_direction = models.IntegerField()


class OutputData(models.Model):
    date_time = models.DateTimeField(auto_now_add=True)
    avg_temperature = models.IntegerField()
    avg_wind_speed = models.IntegerField()
    direction_in_space = models.IntegerField()

weatherapi/api/views.py
from rest_framework.generics import ListAPIView
from .serializers import OutputDataSerializer, InputDataSerializer
from ..models import OutputData, InputData


class OutputDataView(ListAPIView):
    serializer_class = OutputDataSerializer
    queryset = OutputData.objects.all()


class InputDataView(ListAPIView):
    serializer_class = InputDataSerializer
    queryset = InputData.objects.all()

weatherapi/views.py
from django.shortcuts import render, redirect
from .models import InputData, OutputData
from . import services

# Create your views here.
def home(request):
    template_name = 'weatherapi\index.html'
    services.calculate_output_data()
    return render(request, template_name)


def clear_data(request):
    InputData.objects.all().delete()
    OutputData.objects.all().delete()
    return redirect('/')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Weather App</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

</head>
<body>

<div class="container mt-5">
    {% block content %}

    {% endblock %}

</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>

weatherapi/templates/weatherapi/index.html
{% extends 'base.html' %}

{% block content %}

    <h3>
        Weather API
        <small class="text-muted">By Bachir Mehemmel</small>
    </h3>
    <hr>

    <p>Get output data at:
    <a href="http://127.0.0.1:8000/api/weather-list/">http://127.0.0.1:8000/api/weather-list/</a>
    </p>

    <p>Get output data at:
    <a href="http://127.0.0.1:8000/api/input-list/">http://127.0.0.1:8000/api/input-list/</a>
    </p>

    <a href="{% url 'weatherapi:clear-data' %}" class="btn btn-secondary">Clear data... </a>





{% endblock %}